[package]
name = "hush"
version = "0.1.0"
authors = ["gahag <gabriel.s.b@live.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
termion = "1.5"

string-interner = { version = "0.12", default-features = false, features = [ "std", "inline-more", "backends" ] }
gc = { version = "0.4", features = ["derive"] }
regex = { version = "1.5", default-features = false, features = [ "std" ]}

[dev-dependencies]
assert_matches = "1.5"

[profile.release]
lto = true
