[package]
name = "hush"
version = "0.1.0"
authors = ["gahag <gabriel.s.b@live.com>"]
edition = "2018"

[dependencies]
string-interner = { version = "0.12", default-features = false, features = [ "std", "inline-more", "backends" ] }


[dev-dependencies]
assert_matches = "1.5"
